---- Adiciona a coluna numero_homens
--ALTER TABLE persons
--ADD COLUMN numero_homens INT DEFAULT 0;
--
---- Adiciona a coluna numero_mulheres
--ALTER TABLE persons
--ADD COLUMN numero_mulheres INT DEFAULT 0;